//! The vault as the iOS AutoFill extension (`app.rowel.mobile.autofill`) reads
//! it: the active workspace's database, found in the App Group container the
//! app keeps it in, opened with the key the app enrolled for Face ID, and read
//! for the logins that belong to the site being filled.
//!
//! Swift does the platform half — the container path, the Face ID prompt, the
//! keychain read — and hands Rust plain strings and bytes. Everything that
//! decides where the vault is, how the key opens it and which logins match is
//! `rowel_core`, the code the app itself runs.
//!
//! The Swift side is generated by UniFFI (`bindgen.sh`).

use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use rowel_core::crypto::{self, PayloadCipher, VaultKey};
use rowel_core::host::{host_matches, site_host};
use rowel_core::keychain::{self, GateMode};
use rowel_core::layout::{
    self, BIOMETRIC_FILE, DB_FILE, DB_REKEY_BACKUP_FILE, KDF_SIDECAR_FILE, WRAPPED_KEY_FILE,
};
use rowel_core::models::Entry;
use rowel_core::store::{SqliteStore, StoreError, VaultStore};
use rowel_core::workspace::{dir_of, Registry, PRIMARY_ID};
use zeroize::Zeroizing;

uniffi::setup_scaffolding!();

/// Why the vault cannot be read. Each case is one thing the extension says.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum AutofillError {
    /// No vault in the container: Rowel was never set up on this device, or
    /// its data is still in the app's own sandbox (an App Group the build was
    /// not entitled to).
    #[error("there is no vault on this device")]
    NoVault,
    /// Nothing here is unlockable without the master password: Face ID unlock
    /// is off, or the active workspace has no key sealed under the app key.
    #[error("unlock with Face ID is not turned on for this vault")]
    Locked,
    /// The key read from the keychain does not open the vault.
    #[error("the Face ID key does not open this vault")]
    WrongKey,
    /// A master-password change was interrupted. The app rolls the vault back
    /// at its next unlock; until then the database and the sealed payloads
    /// may be on different keys, and nothing here writes.
    #[error("Rowel is finishing a password change")]
    Recovering,
    /// Nothing to fill under that record for that site: the login is gone,
    /// another workspace's, moved to another site, or has no password.
    #[error("no such login")]
    NotFound,
    #[error("{message}")]
    Io { message: String },
}

impl From<StoreError> for AutofillError {
    fn from(e: StoreError) -> Self {
        match e {
            StoreError::WrongKey => Self::WrongKey,
            e => Self::Io {
                message: e.to_string(),
            },
        }
    }
}

impl From<rowel_core::error::Error> for AutofillError {
    fn from(e: rowel_core::error::Error) -> Self {
        Self::Io {
            message: e.to_string(),
        }
    }
}

/// The active vault's place, and the keychain item its key is in. Read
/// without the key: what Swift needs to know before it asks for Face ID.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct VaultLocation {
    /// The data dir: `<container>/app.rowel.mobile`, and its `dev` subdir in a
    /// debug build, as the app lays it out (`layout::app_group_root`).
    pub root: String,
    /// The active workspace, as the registry names it.
    pub workspace: String,
    /// The generic-password item holding the app key, in the App Group's
    /// keychain access group: the account is the one for the gate the app
    /// enrolled behind.
    pub keychain_service: String,
    pub keychain_account: String,
}

/// A login offered for the site, with nothing secret in it: a row's name, the
/// name it signs in with and its site. `record` is the credential identity's
/// `"<workspace id>/<entry id>"`, as the app publishes it to iOS.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct Credential {
    pub record: String,
    pub title: String,
    pub user: String,
    pub host: String,
}

/// What a chosen login fills.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct Password {
    pub user: String,
    pub password: String,
}

/// The App Group the vault and the key are shared through — one spelling for
/// the Swift side as well (`rowel_core::app::APP_GROUP`).
#[uniffi::export]
pub fn app_group() -> String {
    rowel_core::app::APP_GROUP.to_string()
}

/// Where the active vault is in the App Group container at `container`, and
/// which keychain item opens it.
#[uniffi::export]
pub fn vault_location(container: String) -> Result<VaultLocation, AutofillError> {
    let root = layout::app_group_root(Path::new(&container));
    let workspace = Registry::load(&root).active;
    let dir = dir_of(&root, &workspace);
    ready(&dir)?;
    // The marker names the gate the key went in behind, and so the item's
    // account. No marker, no key.
    let marker =
        fs::read_to_string(root.join(BIOMETRIC_FILE)).map_err(|_| AutofillError::Locked)?;
    let keychain_account = match GateMode::from_marker(&marker) {
        GateMode::Protected => keychain::ACCOUNT,
        GateMode::Prompt => keychain::ACCOUNT_PROMPT,
        GateMode::HelloKey => return Err(AutofillError::Locked),
    };
    // The stored key is the app key, the primary's; any other workspace opens
    // through its own key sealed under it, and one without is not offered a
    // Face ID unlock by the app either.
    if workspace != PRIMARY_ID && !dir.join(WRAPPED_KEY_FILE).exists() {
        return Err(AutofillError::Locked);
    }
    Ok(VaultLocation {
        root: root.to_string_lossy().into_owned(),
        workspace,
        keychain_service: keychain::SERVICE.to_string(),
        keychain_account: keychain_account.to_string(),
    })
}

/// Open the vault at `location` with `key`, the bytes of its keychain item.
#[uniffi::export]
pub fn open_vault(location: VaultLocation, key: Vec<u8>) -> Result<Arc<Vault>, AutofillError> {
    let dir = dir_of(&PathBuf::from(&location.root), &location.workspace);
    ready(&dir)?;
    let app_key = Zeroizing::new(key);
    let material = if location.workspace == PRIMARY_ID {
        app_key
    } else {
        let sealed =
            fs::read_to_string(dir.join(WRAPPED_KEY_FILE)).map_err(|e| match e.kind() {
                std::io::ErrorKind::NotFound => AutofillError::Locked,
                _ => AutofillError::Io {
                    message: e.to_string(),
                },
            })?;
        crypto::open_workspace_key(&app_key, &location.workspace, &sealed)
            .map_err(|_| AutofillError::WrongKey)?
    };
    // As the app reads the same bytes: an Argon2id master where there is a
    // KDF sidecar, the legacy secret where there is none.
    let key = VaultKey::from_material(material, dir.join(KDF_SIDECAR_FILE).exists());
    let store = SqliteStore::open(&dir.join(DB_FILE), key.sqlcipher_key().as_slice())?;
    Ok(Arc::new(Vault {
        workspace: location.workspace,
        store,
        cipher: key.payload_cipher(),
    }))
}

// Whether the vault at `dir` is one to open: there, and not in the middle of
// a password change. Checked before the key is asked for and again before the
// open — `SqliteStore::open` makes a database where there is none, and the
// extension must never be what creates a vault.
fn ready(dir: &Path) -> Result<(), AutofillError> {
    if !fs::metadata(dir.join(DB_FILE)).is_ok_and(|m| m.len() > 0) {
        return Err(AutofillError::NoVault);
    }
    if dir.join(DB_REKEY_BACKUP_FILE).exists() {
        return Err(AutofillError::Recovering);
    }
    Ok(())
}

/// The sites iOS is filling for, as hosts. `None` is no site to go by — iOS
/// named none — and every login is admitted; otherwise a login is admitted by
/// the rule the browser extension fills by (`host_matches`): the site itself
/// or a parent of it, never across a public suffix. The list and the fill
/// both go through here, so a record iOS still holds for a site its login has
/// since been moved off is refused the same way it would be left off the list.
struct Sites(Option<Vec<String>>);

impl Sites {
    fn named(identifiers: &[String]) -> Self {
        Self((!identifiers.is_empty()).then(|| {
            identifiers
                .iter()
                .filter_map(|id| service_host(id))
                .collect()
        }))
    }

    fn admit(&self, host: &str) -> bool {
        self.0
            .as_ref()
            .is_none_or(|sites| sites.iter().any(|site| host_matches(site, host)))
    }
}

/// An open vault. Lives as long as the extension's sheet.
#[derive(uniffi::Object)]
pub struct Vault {
    workspace: String,
    store: SqliteStore,
    cipher: PayloadCipher,
}

#[uniffi::export]
impl Vault {
    /// The logins for the sites iOS names — each identifier a domain or a
    /// URL, admitted by [`Sites`] — that have a password to fill
    /// ([`fills_password`]). The listing is read for all of them; a row is
    /// unsealed only when the listing cannot vouch for it, and then for the
    /// same two things the fill needs — the name it signs in with
    /// (`Entry::login_name`, the name the app publishes to QuickType for the
    /// same row) and whether there is a password at all. The list carries the
    /// name, and nothing else of the payload.
    pub fn credentials_for(
        &self,
        service_identifiers: Vec<String>,
    ) -> Result<Vec<Credential>, AutofillError> {
        let sites = Sites::named(&service_identifiers);
        let mut credentials = Vec::new();
        for meta in self.store.list()? {
            if meta.kind != "login" || !sites.admit(&meta.url_host) {
                continue;
            }
            let username = meta.username.as_deref().filter(|u| !u.is_empty());
            let user = match username {
                Some(user) if listing_vouches(meta.has_passkey, username) => user.to_string(),
                // A row that will not unseal is left off rather than failing
                // the list: the key opened the database, so it is that row's
                // alone — and it could not be filled either.
                _ => match self.entry(&meta.id) {
                    Ok(Some(entry)) if fills_password(meta.has_passkey, username, &entry) => {
                        sign_in_name(&entry)
                    }
                    _ => continue,
                },
            };
            credentials.push(Credential {
                record: format!("{}/{}", self.workspace, meta.id),
                user,
                title: meta.title,
                host: meta.url_host,
            });
        }
        Ok(credentials)
    }

    /// The name and password `record` fills, unsealing that row alone — for
    /// the sites iOS is filling for, which it names as it does for the list.
    /// The row is admitted by the rule the list is, checked here again against
    /// the vault rather than trusted from what iOS holds: a QuickType
    /// suggestion the app published before the login was moved to another
    /// site, or deleted, is `NotFound`, not the login's current password
    /// filled into its former site.
    pub fn password(
        &self,
        record: String,
        service_identifiers: Vec<String>,
    ) -> Result<Password, AutofillError> {
        let id = record
            .split_once('/')
            .filter(|(workspace, _)| *workspace == self.workspace)
            .map(|(_, id)| id)
            .ok_or(AutofillError::NotFound)?;
        // `get` answers nothing for a row in the trash.
        let row = self.store.get(id)?.ok_or(AutofillError::NotFound)?;
        if row.kind != "login" || !Sites::named(&service_identifiers).admit(&row.url_host) {
            return Err(AutofillError::NotFound);
        }
        let entry = self.cipher.unseal(&row.id, &row.payload)?;
        if !fills_password(row.has_passkey, row.username.as_deref(), &entry) {
            return Err(AutofillError::NotFound);
        }
        Ok(Password {
            user: sign_in_name(&entry),
            password: entry.password.clone().unwrap_or_default(),
        })
    }
}

impl Vault {
    // The row `id` unsealed, or `None` when there is no such row.
    fn entry(&self, id: &str) -> Result<Option<Entry>, AutofillError> {
        let Some(row) = self.store.get(id)? else {
            return Ok(None);
        };
        Ok(Some(self.cipher.unseal(&row.id, &row.payload)?))
    }
}

/// The name a login signs in with, as the list shows it and the fill sends
/// it: `Entry::login_name`, trimmed — the listing's `username` column is the
/// trimmed one (`store::migrate::derived_username`), and the app trims it for
/// QuickType too, so the three name an account alike.
fn sign_in_name(entry: &Entry) -> String {
    entry.login_name().unwrap_or_default().trim().to_string()
}

/// Whether a login's listing — its `has_passkey` and `username` columns —
/// vouches for it having a password to fill: a login with a username and no
/// passkey does, as far as the app's QuickType identities are concerned
/// (`credential_identities::needs_entry` in the app unseals exactly the rest).
/// A row with no username column, or a passkey on it — the passkey-only kind
/// an import brings has no password — the listing cannot vouch for.
fn listing_vouches(has_passkey: bool, username: Option<&str>) -> bool {
    !has_passkey && username.is_some_and(|u| !u.is_empty())
}

/// Whether a login has a password to fill: the one rule for the list and the
/// fill, so nothing is offered that will not fill and nothing refused that
/// was offered. The listing's word where it vouches ([`listing_vouches`]),
/// the payload's otherwise.
fn fills_password(has_passkey: bool, username: Option<&str>, entry: &Entry) -> bool {
    listing_vouches(has_passkey, username) || entry.has_password()
}

// The host a service identifier names: iOS passes a URL for a web page and a
// bare domain for an app's associated domain, and both read here the way a
// browser's page does for the browser host.
fn service_host(identifier: &str) -> Option<String> {
    let identifier = identifier.trim();
    if identifier.is_empty() {
        return None;
    }
    site_host(identifier).or_else(|| site_host(&format!("https://{identifier}")))
}

#[cfg(test)]
mod tests;
