// Extracts the browser extension's theme tokens
// (extension/rowel/css/rowel-tokens.css) from the desktop app's design tokens
// in src/styles/theme.css, so the extension's popup, options pages and in-page
// UI (autocomplete, banner, notification) wear the app's palette, fonts and
// radii. theme.css is the single source of truth: nothing here spells out a
// colour, and the file is re-generated after every change to it.
//
// The tokens file mirrors colors.css's four selector blocks (light by default,
// dark by media query, and either forced through `data-bs-theme`), and holds
// only values: the `--c-*` tokens, the rgb triplets Bootstrap composes with an
// alpha, and the check/switch glyphs whose fill is baked into an SVG. The
// rules that use them are hand-written in css/rowel.css, which imports it.
//
// `--check` changes nothing and exits 1 if the file is stale (CI).
import { readFileSync, writeFileSync } from 'node:fs'

const THEME = 'src/styles/theme.css'
const OUT = 'extension/rowel/css/rowel-tokens.css'

// The tokens rowel.css uses, by their theme.css names. Every one has to exist
// in both palettes.
const names = list => list.trim().split(/\s+/)
const TOKENS = names(`
  --c-rail --c-detail --c-pane --c-list --c-field --c-tile --c-line --c-line2
  --c-hover --c-sel --c-lens --lens-shadow --c-text --c-text2 --c-text3 --c-brand
  --c-accent --c-accent-fg --c-accent-soft --c-accent-line --c-accent-hover
  --c-good --c-warn --c-bad --c-bad-hover --c-lockfield
  --menu-line --menu-shadow --shadow --card-shadow --thumb --menu`)
// The ones Bootstrap's utilities (`.bg-*`, `.text-*`, `a`, `.alert-*`) compose
// with an alpha: each also gets a `-rgb` triplet, so it has to be a hex colour.
const RGB = names(`
  --c-detail --c-text --c-text2 --c-text3 --c-list --c-pane --c-accent
  --c-accent-hover --c-good --c-warn --c-bad --c-lockfield`)
const FONTS = ['--font-sans', '--font-mono']
// Type scale tokens from the `@theme` block, the same in both palettes.
const TYPE = ['--tracking-label', '--tracking-display']

const source = readFileSync(THEME, 'utf8').replace(/\/\*[\s\S]*?\*\//g, '')

// The declarations of one top-level `<selector> {` block (none nest braces
// once the comments are gone).
function declarations(selector) {
  const open = `${selector} {`
  const at = source.indexOf(open)
  if (at === -1) throw new Error(`${THEME}: no \`${open}\` block`)
  const body = source.slice(at + open.length, source.indexOf('}', at))
  const vars = {}
  for (const [, name, value] of body.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) {
    vars[name] = value.replace(/\s+/g, ' ').trim()
  }
  return vars
}

function pick(vars, names, where) {
  const missing = names.filter(name => !(name in vars))
  if (missing.length) throw new Error(`${THEME}: ${where} lacks ${missing.join(', ')}`)
  return Object.fromEntries(names.map(name => [name, vars[name]]))
}

const light = pick(declarations(':root'), TOKENS, ':root')
const dark = pick(declarations(":root[data-theme='dark']"), TOKENS, ":root[data-theme='dark']")
const type = {
  ...pick(declarations('@theme inline'), FONTS, '@theme inline'),
  ...pick(declarations('@theme'), TYPE, '@theme')
}

const rgb = (name, value) => {
  const hex = /^#([0-9a-f]{6})$/i.exec(value)
  if (!hex) throw new Error(`${name} is ${value}; a 6-digit hex colour is needed to derive its rgb triplet`)
  return [0, 2, 4].map(i => parseInt(hex[1].slice(i, i + 2), 16)).join(', ')
}
const svg = body =>
  `url("data:image/svg+xml,${encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' ${body}</svg>`)}")`

// One palette's values.
function palette(t) {
  const out = TOKENS.map(name => `${name}: ${t[name]};`)
  for (const name of RGB) out.push(`${name}-rgb: ${rgb(name, t[name])};`)
  // Bootstrap's check marks are white; on a filled accent they need accent-fg.
  const fg = t['--c-accent-fg']
  out.push(
    `--rowel-check-mark: ${svg(`viewBox='0 0 20 20'><path fill='none' stroke='${fg}' stroke-linecap='round' stroke-linejoin='round' stroke-width='3' d='m6 10 3 3 6-6'/>`)};`,
    `--rowel-radio-dot: ${svg(`viewBox='-4 -4 8 8'><circle r='2' fill='${fg}'/>`)};`,
    `--rowel-switch-knob: ${svg(`viewBox='-4 -4 8 8'><circle r='3' fill='${fg}'/>`)};`,
    `--rowel-switch-knob-focus: ${svg(`viewBox='-4 -4 8 8'><circle r='3' fill='${t['--c-text2']}'/>`)};`
  )
  return out
}

const block = (selector, lines, depth = 0) => {
  const pad = ' '.repeat(depth)
  return `${pad}${selector.replace(/,\s*/g, `,\n${pad}`)} {\n${lines.map(line => `${pad}    ${line}`).join('\n')}\n${pad}}`
}

const next = `/*
 * generated by scripts/extension-theme.mjs from src/styles/theme.css, do not edit
 * (change the tokens there and run \`bun run extension:theme\`). Values only,
 * in the same four blocks as colors.css; the rules that use them are in
 * rowel.css.
 */

${block(':root, :host', palette(light))}

@media (prefers-color-scheme: dark) {
${block(':root, :host', palette(dark), 4)}
}

/* Same colours for manual switching */
${block("[data-bs-theme='dark']", palette(dark))}

${block("[data-bs-theme='light']", palette(light))}

/* Type: the same in both themes. */
${block(':root, :host', Object.entries(type).map(([name, value]) => `${name}: ${value};`))}
`

const check = process.argv.includes('--check')
let current
try {
  current = readFileSync(OUT, 'utf8')
} catch {
  current = ''
}

if (next === current) {
  console.log(check ? 'Extension theme is generated.' : `${OUT} is up to date.`)
} else if (check) {
  console.error(`Stale (run \`bun run extension:theme\`): ${OUT}`)
  process.exit(1)
} else {
  writeFileSync(OUT, next)
  console.log(`Wrote ${OUT}.`)
}
